version: "3.3"

services:
  nooptime:
    image: nooptime
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - Database:ConnectionString=server=postgres;port=5432;database=nooptime;uid=nooptime;pwd=nooptime;
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=nooptime
      - POSTGRES_PASSWORD=nooptime
